#---------------------------------#
#  Build Image                    #
#---------------------------------#

image: Visual Studio 2019

#---------------------------------#
#  Init                           #
#---------------------------------#

init:
  - git config --global core.autocrlf true

#---------------------------------#
#  Build Script                   #
#---------------------------------#

build_script:
  - ps: Get-ChildItem -Path "C:\Program Files (x86)\Microsoft SDKs\TypeScript\*" -Include tsc.exe,tsc.js -Recurse | Rename-Item -NewName {$_.name -replace "tsc","tsc1"}
  - ps: .\build.ps1 --target="AppVeyor"

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#

branches:
  # Whitelist
  only:
    - develop
    - master
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#

cache:
- tools -> recipe.cake
- node_modules -> package.json
